[HOPSWORKS-1849]
logicalclocks/expat pull request #39
Opened 2020-08-14 08:35 UTC by ErmiasG

2020-08-14 08:36 UTC, ErmiasG commented
logicalclocks/hops-testing-ee/pull/130

2020-09-01 08:07 UTC, o-alex commented on src/main/java/io/hops/hopsworks/expat/migrations/dataset/FixDatasetPermission.java
> +      throw new MigrationException("error", e);
replace "error" with "acl" maybe ... so it is clear which step failed - for example in 1.4 we have docker and acl

2020-09-01 08:07 UTC, o-alex requested changes

2020-09-01 08:07 UTC, o-alex commented on src/main/java/io/hops/hopsworks/expat/migrations/dataset/FixDatasetPermission.java
> +      throw new RollbackException("error", e);
same as above

2020-09-01 08:11 UTC, o-alex approved these changes

2020-09-01 08:11 UTC, merged